name: Java Backend CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Backend
        working-directory: backend
        run: mvn clean package -DskipTests

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /root/Java-springboot-project

            git fetch origin
            git reset --hard origin/main

            cd backend

            mvn clean package -DskipTests

            sudo systemctl restart datastore-backend

            sudo systemctl status datastore-backend --no-pager

            echo "Deployment Successful"
