name: Backend to EC2

on:
  workflow_dispatch:
  
  - name: Deploy Application
  uses: appleboy/ssh-action@v1.1.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ec2-user
    key: ${{ secrets.EC2_KEY }}
    script: |
      set -e

      cd /home/ec2-user/app/Java-springboot-project/backend

      # Build the latest JAR
      mvn clean package -DskipTests

      # Restart the Spring Boot service
      sudo systemctl daemon-reload
      sudo systemctl restart datastore

      # Wait for application to start
      sleep 20

      # Check service status
      sudo systemctl status datastore --no-pager

      # Health check
      curl -f http://localhost:8084/actuator/health
