name: Build, Scan, Push to ECR and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  BACKEND_REPO: backend
  FRONTEND_REPO: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    ##################################################
    # Checkout
    ##################################################

    - name: Checkout Repository
      uses: actions/checkout@v4

    ##################################################
    # Java Setup
    ##################################################

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    ##################################################
    # Build
    ##################################################

    - name: Build Backend
      working-directory: backend
      run: mvn clean package -DskipTests

    ##################################################
    # SonarQube Scan
    ##################################################

    - name: SonarQube Scan
      working-directory: backend
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=backend \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN

    ##################################################
    # Configure AWS
    ##################################################

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    ##################################################
    # Login ECR
    ##################################################

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    ##################################################
    # Create Repositories
    ##################################################

    - name: Create ECR Repositories
      run: |
        aws ecr describe-repositories --repository-names $BACKEND_REPO >/dev/null 2>&1 || \
        aws ecr create-repository --repository-name $BACKEND_REPO

        aws ecr describe-repositories --repository-names $FRONTEND_REPO >/dev/null 2>&1 || \
        aws ecr create-repository --repository-name $FRONTEND_REPO

    ##################################################
    # Docker Build
    ##################################################

    - name: Build Backend Docker Image
      run: |
        docker build -t backend:latest ./backend

    - name: Build Frontend Docker Image
      run: |
        docker build -t frontend:latest ./frontend

    ##################################################
    # Trivy Installation
    ##################################################

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
        gpg --dearmor | \
        sudo tee /usr/share/keyrings/trivy.gpg >/dev/null

        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
        sudo tee /etc/apt/sources.list.d/trivy.list

        sudo apt-get update
        sudo apt-get install trivy -y

    ##################################################
    # Trivy Scan
    ##################################################

    - name: Scan Backend Image
      run: |
        trivy image backend:latest

    - name: Scan Frontend Image
      run: |
        trivy image frontend:latest

    ##################################################
    # Tag Images
    ##################################################

    - name: Tag Images
      run: |
        docker tag backend:latest \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO:latest

        docker tag frontend:latest \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO:latest

    ##################################################
    # Push Images
    ##################################################

    - name: Push Backend Image
      run: |
        docker push \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO:latest

    - name: Push Frontend Image
      run: |
        docker push \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO:latest

    ##################################################
    # Deploy EC2
    ##################################################

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}

        script: |

          aws ecr get-login-password \
          --region ${{ secrets.AWS_REGION }} | \
          sudo docker login \
          --username AWS \
          --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

          sudo docker pull \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend:latest

          sudo docker pull \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend:latest

          sudo docker stop backend || true
          sudo docker rm backend || true

          sudo docker stop frontend || true
          sudo docker rm frontend || true

          sudo docker run -d \
          --name backend \
          -p 8084:8084 \
          -e SPRING_DATASOURCE_URL="jdbc:mysql://alisha-db.cetueqgig5p3.us-east-1.rds.amazonaws.com:3306/datastore?createDatabaseIfNotExist=true" \
          -e SPRING_DATASOURCE_USERNAME="admin" \
          -e SPRING_DATASOURCE_PASSWORD="alisha123" \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend:latest

          sudo docker run -d \
          --name frontend \
          -p 8501:8501 \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend:latest

    ##################################################
    # Verify
    ##################################################

    - name: Verify Containers
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker ps
          sudo docker images

    ##################################################
    # Email Notification
    ##################################################

    - name: Send Email Notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true

        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}

        subject: GitHub Actions Pipeline - ${{ job.status }}

        to: your-email@gmail.com
        from: GitHub Actions

        body: |
          Pipeline Status: ${{ job.status }}

          Repository: ${{ github.repository }}

          Branch: ${{ github.ref_name }}

          Commit: ${{ github.sha }}

          Workflow: ${{ github.workflow }}

          Run URL:
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
